import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import MuiThemeProvider from "../components/MuiThemeProvider";
import "./globals.css";
import React from "react";
import ResponsiveAppBar from "@/components/Appbar/ResponsiveAppBar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <MuiThemeProvider>
            {/* <div className="logo">
              <h1>My Logo</h1>
            </div> */}
            <ResponsiveAppBar />
            {children}
          </MuiThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
